chown -R valet:valet /etc/valet
chmod 0750 /etc/valet

chown -R valet:valet /opt/app/valet/tools
chmod 755 /opt/app/valet/tools/*

chown valet:valet /var/log/valet
chmod 0750 /var/log/valet

chown valet:valet /var/run/valet
chown valet:valet /var/www/valet/app.wsgi
chown valet:valet /var/www/valet/config.py

find /var/lib/valet -xdev -type d -exec chown valet:valet {} \;

ln -s /etc/apache2/sites-available/180-valet.conf /etc/apache2/sites-enabled/180-valet.conf
